/* eslint-disable react/prop-types */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/models/Rabbit.glb -o src/components/content/canvas/maps/player/Rabbit.jsx 
*/

import { useGLTF } from "@react-three/drei";
import { usePlayer } from "./hooks/usePlayer";

export function Rabbit({ player, position, modelIndex }) {
  const { playerRef, memoizedPosition, playerId, nodes, materials } = usePlayer(
    {
      player,
      position,
      modelIndex: modelIndex ?? player.selectedCharacterGlbNameIndex,
    }
  );

  return (
    <group
      ref={playerRef}
      position={memoizedPosition}
      name={playerId ?? ""}
      dispose={null}
    >
      <group name="Root_Scene">
        <group name="RootNode">
          <group name="Character" scale={0.6}>
            <group name="CharacterArmature" scale={1}>
              <primitive object={nodes.Root} />
            </group>
            <skinnedMesh
              name="Atlas"
              geometry={nodes.Atlas.geometry}
              material={materials.white}
              skeleton={nodes.Atlas.skeleton}
              scale={0.01}
            />
            <skinnedMesh
              name="Atlas_1"
              geometry={nodes.Atlas_1.geometry}
              material={materials.pink}
              skeleton={nodes.Atlas_1.skeleton}
              scale={0.01}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/Rabbit.glb");
